# Performance comparison of ndarray creation
An ndarray of 2 x 2 matrix needs to be created.

The following options are compared:
 1. Create an ndarray of [0, 1, 2, 3, 4, 5] first, and create an ndarray of 2 x 2 matrix by calling np.append function.
 2. Create a Python list of [0, 1, 2, 3, 4, 5] first, create a 2 x 2 matrix in Python list by appending it, and create an ndarray of 2 x 2 matrix from the 2 x 2 matrix in Python list.
 3. Create an ndarray of [[0], [10], [20], [30], [40], [50]] first, and add ndarray of [0, 1, 2, 3, 4, 5]
 
The result is that the options are faster in ascending order.

The followings are reasons for this performance difference.
 1. The size of an ndarray instance is fixed, so calling np.append function creates new instance of ndarray, which results in new memory allocation of all the existing elements and to-be-appended elements in ndarray. (In C++, this is like the built-in array.)
 2. Python list holds memory more than currently required elements and appending elements results in new memory allocation only when the allocated memory is exhausted. (In C++, this is like std::vector.)
 3. Memory allocation happens only three times for 1. np.arange(0, 51, 10), 2. np.arange(6), and 3. the result of + operator.


In [1]:
import numpy as np

In [2]:
def create_by_np_append():
    top_row = np.arange(6)
    matrix = np.array([top_row])
    for i in range(1, 6):
        matrix = np.append(matrix, np.array([top_row + i*10]), axis=0)
    return matrix

create_by_np_append()

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [3]:
%timeit create_by_np_append()

23.2 µs ± 1.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
def create_by_list_append():
    top_row = range(6)
    matrix = [list(top_row)]
    for i in range(1, 6):
        matrix.append([item + i * 10 for item in top_row])
    return np.array(matrix)

create_by_list_append()

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [5]:
%timeit create_by_list_append()

8.66 µs ± 248 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
def create_by_adding_ndarray():
    return np.arange(0, 51, 10)[:, np.newaxis] + np.arange(6)

create_by_adding_ndarray()

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [7]:
%timeit create_by_adding_ndarray()

3.81 µs ± 262 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
