Doing http://www.scipy-lectures.org/intro/numpy/array_object.html

Resume from 1.3.1.2. Creating arrays

In [1]:
import numpy as np

In [2]:
%matplotlib inline

In [3]:
import matplotlib.pylab as plt

In [4]:
a = np.arange(10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[0], a[2], a[-1]

(0, 2, 9)

In [7]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
a = np.diag(np.arange(3))

In [9]:
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [10]:
a[1, 1]

1

In [11]:
a[2, 1] = 10

In [12]:
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [13]:
a[1]

array([0, 1, 0])

In [14]:
a = np.arange(10)

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[2:9:3]

array([2, 5, 8])

In [83]:
def np_append():
    top_row = np.arange(6)
    matrix = np.array([top_row])
    for i in range(1, 6):
        matrix = np.append(matrix, np.array([top_row + i*10]), axis=0)
    return matrix

%timeit np_append()

27.2 µs ± 3.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [84]:
def list_append():
    top_row = range(6)
    matrix = [list(top_row)]
    for i in range(1, 6):
        matrix.append([item + i * 10 for item in top_row])
    return np.array(matrix)

%timeit list_append()

8.79 µs ± 253 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
